### ISSUE TITLE
rstcheck doesn't recognize the ::code-block :caption: 

### ISSUE THREAD

**Issue by Feng-Yin** [myint/rstcheck#62] opened 2019-11-25 04:27 UTC
rstcheck doesn't support below syntax.

```
.. code-block:: yaml
   :caption: **caption**
```

**Comment by phlax** [comment] 2021-03-31 13:04
my problem went away on installing sphinx

**Comment by Cielquan** [comment] 2022-04-16 11:46
If sphinx is installed the example in the OP does not throw an error.

rstcheck: 4.0.0
python 3.8.10

Adding `:emphasize-lines:` does however error.

**Comment by Cielquan** [comment] 2022-04-18 12:25
The OP issue will when #94 is merged result in an `(ERROR/3) Error in "code-block" directive:` unless Sphinx is also installed.

**Comment by Cielquan** [comment] 2022-04-18 13:16
And now also all other roles on `code-block` should be fine then.

**Comment by Cielquan** [comment] 2022-04-18 13:29
Nevermind .. the issue is much more complex after all.

**Comment by Cielquan** [comment] 2022-04-18 15:21
Now it should be also fixed in #94.

The OP issue is fixed when you have sphinx installed.

The example by @phlax is also fixed. I did not use :emphasize-lines: correct and therefore the error for me was correct.

The snippet below is error free with #94 and sphinx installed.

```rst
.. code-block:: yaml
   :caption: **caption**
   :emphasize-lines: 1

   ---
   
```

**Closed** 2022-04-18 15:36 UTC
Labels: bug, help wanted
